# Generated by Django 6.0.6 on 2026-06-12 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_brand_product_category_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='full_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='size_qty',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='variant',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
